name: Mad-Dam adventures
description: Back to comics ! Mad-Dam is on the stage
pygments: true
permalink: /:year/:month/:title/
baseurl: /mad-dam
url: https://maxiimou.github.io/
author:
    name: "G.A.G Team & Co"

markdown: redcarpet
